config/routes.rb
Rails.application.routes.draw do
  # get 'profiles/new'
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "groups#index"
  resources :users, only: [:index, :new, :create, :show, :edit, :update] do
  resources :groups, only: [:new, :create, :edit, :update] 
end

  # マイページ
  resources :mypage, only: [:index, :edit, :update, :destroy, :show] do
    resources :comments, only: [:index, :create]
    member do
      get :profile
      get :message
    end
  end

  # マイページ
  resources :profiles
  #  only: [:index, :edit, :update, :destroy, :show] do
  # end

    # 新規登録ページ
    resources :signup do
      collection do
        get :step1 # ここで、入力の全て完了
        get :step2
        get :done # 登録完了後のページ
      end
    end
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user

  enum gender: { '男性': 0, '女性': 1 }
  enum job: { '学生': 0, '会社員': 1, '自営業': 2, 'その他': 3 }
  enum holiday: { '土日祝': 0, '平日': 1, 'シフト': 2, '他': 3 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :move_to_index

  def index
    # binding.pry
    @user = User.find(current_user.id)
  end

  def profile
  end
  
  def message
  end

  def edit
    # binding.pry
    @profile = Profile.find(current_user.id)
  end

  def show
    @profile = @profile.message
    @profile = Profile.find(params[:profile_id])
  end


  def update
    # binding.pry
    @profile = Profile.find(current_user.id)
    if @profile.update(current_user.id)
      redirect_to profile_mypage_path(@profile)
    else
      render :edit
    end
    # binding.pry
  end

  # def update
  #   @profile = Profile.find(params[:id])
  #   # binding.pry
  #   if profile.user_id == current_user.id
  #     profile.update(profile_params)
  #   end
  # end

  private
  def move_to_index
    redirect_to root_path unless user_signed_in?
  end
  def user_params
    params.require(:user).permit(
      :nickname
    )
  end
  def profile_params
    # binding.pry
    params.require(:profile).permit(:message[:id])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
= render partial:"groups/header"
= render partial:"mypage/side_bar"

.profile_content
  = form_with  model: @profile, url:mypage_path, method: :patch, class: '', local: true do |f|
    .profile_image
      %h4 profile
      .profile_image_nickname 
      = image_tag 'back_image.jpg',class:'profile_img'
      .profile_edit
      = f.submit "profileを更新する", class: "profile_edit_button"
      -# = link_to '編集', '/mypage/:id/edit', method: :get
      = image_tag 'nickname2.jpg',class:'profile_img_nickname',height:'200',width:'200px'  
      %h4 
      = link_to current_user.nickname, '#', class:'profile_img_nickname'

      .profile_detail
        .profile_message
          = text_area :profile, :message, class: 'message_area'
          -# = text_area current_profile.message, class: 'message_area', '#'
          -# = form_for @profile, url: '/mypage/:id', class: 'message_area' do
            -# = text_area :profile, :message, value: '', class: 'message_area'

app/views/profiles/index.html.haml
= render partial:"groups/header"
= render partial:"mypage/side_bar"
.header-logo__wrap
  .sidenav
    = link_to edit_profile_path(@user) do
      = fa_icon "user"
      マイページ