config/routes.rb
Rails.application.routes.draw do
  # get 'profiles/new'
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "groups#index"
  resources :users, only: [:index, :new, :create, :show, :edit, :update] do
  resources :groups, only: [:new, :create, :edit, :update] 
end

  # マイページ
  resources :mypage, only: [:index, :edit, :update, :destroy, :show] do
    resources :comments, only: [:index, :create]
    member do
      get :profile
      get :message
    end
  end

  # マイページ
  resources :profiles
  #  only: [:index, :edit, :update, :destroy, :show] do
  # end

    # 新規登録ページ
    resources :signup do
      collection do
        get :step1 # ここで、入力の全て完了
        get :step2
        get :done # 登録完了後のページ
      end
    end
end

app/models/group.rb
class Group < ApplicationRecord
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]


  def index

  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  
  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/views/groups/_footer.html.haml
%footer
  .footer-container
    .footer-right
      %ul
        %li
          = link_to'/', class: 'footer-item' do
            ミッション
        %li
          = link_to'/', class: 'footer-item' do
            行動指針
        %li
          = link_to'/', class: 'footer-item' do
            サービス
        %li
          = link_to'/', class: 'footer-item' do
            会社概要
        %li
          = link_to'/', class: 'footer-item' do
            お問い合わせ
    .footer-left
      %p 2019 Life_sports_site. All Rights Reserved
    .footer-clear

app/views/groups/_header.html.haml
%body
  - if user_signed_in?
    %header.cmn-header__pc-mode
      .cmn-header__bg--wrap
        .cmn-header__wrap
          .nav-pc
            %ul.nav-pc__on
              %li.nav-pc__on--child.nav-blank
                = link_to destroy_user_session_path,data: { confirm: "ログアウトしてもよろしいですか？" }, method: :delete, class: 'btn btn-danger' do
                  ログアウト
              %li.nav-pc__on--child.nav-blank
                = link_to mypage_index_path, method: :get, class: 'btn btn-primary' do
                  マイページ
  - else
    %header.cmn-header__pc-mode
      .cmn-header__bg--wrap
        .cmn-header__wrap
          .nav-pc
            %ul.nav-pc__on
              %li.nav-pc__on--child.nav-blank
                = link_to new_user_registration_path, class: 'btn btn-primary' do
                  新規登録
              %li.nav-pc__on--child.nav-blank
                = link_to user_session_path, class: 'btn btn-success' do
                  ログイン画面
.header-logo__wrap
  %h6
    = link_to '/', class: '' do
      %span Life Sports Site
-# .text
-#   .content
-#   .dash

%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => "/"} 一覧
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "/"}
          Home
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{:href => "/"} Link
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          カテゴリ
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "/"} 野球
          %a.dropdown-item{:href => "/"} サッカー
          .dropdown-divider
          %a.dropdown-item{:href => "/"} 水泳
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          場所
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "/"} 球場
          %a.dropdown-item{:href => "/"} アリーナ
          .dropdown-divider
          %a.dropdown-item{:href => "/"} その他
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          仲間
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "/"} 遊び
          %a.dropdown-item{:href => "/"} 真剣
          .dropdown-divider
          %a.dropdown-item{:href => "/"} その他
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          その他
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "/"} Q&A
          %a.dropdown-item{:href => "/"} ...
          .dropdown-divider
          %a.dropdown-item{:href => "/"} ...
      %li.nav-item
        %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"}
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/groups/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Life SPORTS
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    -# MEMO:スライダー※簡易プラグイン使用var.
    %link{href: "https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css", rel: "stylesheet"}/
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
    %script{src: "https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"}
    :javascript
      $(document).on('turbolinks:load', function(){
          $('#slider').bxSlider({
              auto: true,
              pause: 5000,
          });
      });

  %body
    = yield

app/views/groups/index.html.haml
<!DOCTYPE html>
%html(lang="ja")
  %head
    %meta(charset="UTF-8")/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")/
    %meta(http-equiv="X-UA-Compatible" content="ie=edge")/
    %title Life SPORTS

    = render partial:"groups/header"

  #carouselExampleFade.carousel.slide.carousel-fade{"data-ride" => "carousel"}
    .carousel-inner
      .carousel-item.active
        = image_tag "20190713_02.jpg",class:"d-block w-100",alt:"...",height:"350px"
      .carousel-item
        = image_tag "main_img.jpg",class:"d-block w-100",alt:"...",height:"350px"
      .carousel-item
        = image_tag "maxresdefault.jpg",class:"d-block w-100",alt:"...",height:"350px"
      .carousel-item
        = image_tag "b602b4bffc5f3a0a01929ae2e1637417.jpg",class:"d-block w-100",alt:"...",height:"350px"
    %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselExampleFade", :role => "button"}
      %span.carousel-control-prev{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.carousel-control-next{"data-slide" => "next", :href => "#carouselExampleFade", :role => "button"}
      %span.carousel-control-next{"aria-hidden" => "true"}
      %span.sr-only Next

    .slider_css
      %ul
        %li
        %li
        -# %li
        -# %li
        -# %li
        
      .main-theme.vision
        %h2 気軽にスポーツが出来る 世の中を創る

    .main-theme.vision__footer
    .main-theme.vision__phone
      = image_tag "phones.png", height:"200px", class: "main-theme.vision__phone"
    .main-theme.vision__text
      = image_tag "appstore_link.png",height:"30px", class: "image", class: "main-theme.vision__text"
      = image_tag "playstore_link.png",height:"30px", class: "image", class: "main-theme.vision__text"

    = render partial:"groups/footer"