config/routes.rb
Rails.application.routes.draw do
  # get 'profiles/new'
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "groups#index"
  resources :users, only: [:index, :new, :create, :show, :edit, :update] do
  resources :groups, only: [:new, :create, :edit, :update] 
end

  # マイページ
  resources :mypage, only: [:index, :edit, :update, :destroy, :show] do
    resources :comments, only: [:index, :create]
    member do
      get :profile
      get :message
    end
  end

  # マイページ
  resources :profiles
  #  only: [:index, :edit, :update, :destroy, :show] do
  # end

    # 新規登録ページ
    resources :signup do
      collection do
        get :step1 # ここで、入力の全て完了
        get :step2
        get :done # 登録完了後のページ
      end
    end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :move_to_index

  def index
    @user = User.find(current_user.id)
    # binding.pry
  end

  def profile
  end
  
  def message
    @user = User.find(current_user.id)
    @comment = Comment.new
    # @profile = Profile.find(params[:id])
    # @old = Old.find_by(id: @profile.old)
    # @prefecture = Prefecture.find_by(id: @profile.prefecture_id)
  end

  def show
    @user = User.find(current_user.id)
    @profile = Profile.find(params[:id])
    @old = Old.find_by(id: @profile.old)
    @prefecture = Prefecture.find_by(id: @profile.prefecture_id)
    @comment = Comment.find_by(params[:mypage_id])
    # binding.pry
  end

  def edit
    # binding.pry
    @user = User.find(current_user.id)
    @profile = Profile.find(params[:id])
  end

  def update
    # binding.pry
    @profile = Profile.find(params[:id])
    @user = User.find(current_user.id)
    # binding.pry
    if @profile.update(profile_params) && @user.update(user_params)
      redirect_to mypage_path(@user)
    else
      render :edit
    end
    # binding.pry
  end

  private
  def move_to_index
    redirect_to root_path unless user_signed_in?
  end
  def user_params
    params.require(:user).permit(
      :nickname
    )
  end
  def profile_params
    # binding.pry
    params.require(:profile).permit(
      :message, 
      :job,
      :holiday, 
      :prefecture_id
      ).merge(user_id: current_user.id)    
  end
  def comment_params
    # binding.pry
    params.require(:comment).permit(
      :comment 
      ).merge(user_id: current_user.id)    
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/_side_bar.html.haml
.header-logo__wrap
  .sidenav
    = link_to mypage_path(@user), method: :get do
      = fa_icon "user"
      マイページ
    = link_to edit_mypage_path(@user), method: :get do
      = image_tag 'nickname.jpg',height: '30', width: '30',class:'user-icon'
      プロフィール
    = link_to mypage_comments_path(@user), method: :get do
      = fa_icon "comment"
      メッセージ
    = link_to "/" do
      = fa_icon "envelope"
      メール/パスワード
    = link_to destroy_user_session_path, method: :delete do
      = fa_icon "sign-out",alt:''
      ログアウト
  .main

app/views/mypage/edit.html.haml
= render partial:"groups/header"
= render partial:"side_bar", group:@user 

.profile_content
  = form_with  model: @user, url:mypage_path, method: :patch, class: '', local: true do |f|
    .profile_image
      %h4 profile
      .profile_image_nickname 
      = image_tag 'back_image.jpg',class:'profile_img'
      .profile_edit
      = f.submit "profileを更新する", class: "profile_edit_button"
      = image_tag 'nickname2.jpg',class:'profile_img_nickname',height:'200',width:'200px' 
      %h4
        = text_area :user, :nickname, class: 'profile_message_area'

    = fields_for @profile, url:mypage_path, method: :patch, class: '', local: true do |o|
      .profile_detail
        .profile_message
          %h5.profile_message_area 職業
          = o.select :job, Profile.jobs.keys.to_a, { prompt: "---" }, class: "message_area"
          %h5.profile_message_area 休日
          = o.select :holiday, Profile.holidays.keys.to_a, { prompt: "---" }, class: "message_area"
          %h5.profile_message_area 居住地
          = o.collection_select :prefecture_id, Prefecture.all, :id, :name, { prompt: "---" }, class: "message_area"
          %h5.profile_message_area 自己紹介
          = text_area :profile, :message, class: 'message_area'

      = render partial:"groups/footer"

app/views/mypage/index.html.haml
= render partial:"groups/header"
= render partial:"side_bar", group: @user

-# .profile_content
-#   .profile_image
-#     %h4 profile
-#     .profile_image_nickname 
-#     = image_tag 'back_image.jpg',class:'profile_img'
-#     = image_tag 'nickname2.jpg',class:'profile_img_nickname',height:'200',width:'200px'   
-#     = link_to current_user.nickname, '#', class:'profile_img_nickname'

-#     .profile_detail
-#       .profile_message
-#         = text_area :profile, :message, class: 'message_area'

      = render partial:"groups/footer"

app/views/mypage/message.html.haml
= render partial:"groups/header"
= render partial:"side_bar", group: @user

.chat-main
  = form_with  model: @comment, url:mypage_comments_path(@user), method: :get, class: '', local: true do |f|
    .chat-main__left-box
      %h5.main-header__left-box__current-group= current_user.nickname 

    .chat-main__form
      .chat-main__form__comment
        = f.text_field :comment, class: 'chat-main__form__comment', placeholder: 'コメントを入力してください'
        .chat-main__comment 
          = f.label :image, class: 'chat-main__image' do
            = fa_icon 'camera', class: 'icon'
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'chat-main__submit'


    = render partial:"groups/footer"

app/views/mypage/show.html.haml
= render partial:"groups/header"
= render partial:"side_bar", group: @user

.profile_content
  .profile_image
    %h4 profile
    .profile_image_nickname 
    = image_tag 'back_image.jpg',class:'profile_img'
    = image_tag 'nickname2.jpg',class:'profile_img_nickname',height:'200',width:'200px'
    %h4.profile_message_area= current_user.nickname

    .profile_detail
      .profile_detail_corner
        .profile_message
        %h5 プロフィール詳細
        .profile_message_corner
          %h5.profile_message_area 年齢
          %span= @old.name
        .profile_message_corner
          %h5.profile_message_area 職業
          %span= @profile.job
        .profile_message_corner
          %h5.profile_message_area 休日
          %span= @profile.holiday
        .profile_message_corner
          %h5.profile_message_area 居住地
          %span= @prefecture.name

      .profile_detail_corner
        .profile_message_corner_introduction
          %h5.profile_message_area 自己紹介
          %span= @profile.message


    = render partial:"groups/footer"